const DATA_PENGALI_TUGAS = 'pengali_nilai_tugas';
const DATA_PENGALI_UTS = 'pengali_nilai_uts';
const DATA_PENGALI_UAS = 'pengali_nilai_uas';

export { DATA_PENGALI_TUGAS, DATA_PENGALI_UTS, DATA_PENGALI_UAS };

const DEFAULT_PENGALI_TUGAS = '20';
const DEFAULT_PENGALI_UTS = '35';
const DEFAULT_PENGALI_UAS = '45';

export { DEFAULT_PENGALI_TUGAS, DEFAULT_PENGALI_UTS, DEFAULT_PENGALI_UAS };


